rails-dashboard/config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }, path: 'auth'

  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'registrations#new', as: :unauthenticated_root
    end
  end

  root 'dashboards#index'

  resources :notifications do
    resources :notification_delivers, only: :update
  end

  resources :smtp_settings, path: 'smtp'
  resources :accounts do
    member do
      post :set_current
    end
  end

  resource :trackings
  resource :test_modes

  resources :invitations, only: %i[create update]

  resources :notification_contents, path: 'templates' do
    member do
      get :preview
    end
  end

  resources :activities, only: %i[index show] do
    resource :schedulers, only: %i[show update]
  end

  resources :dashboards, only: :index
end

rails-dashboard/app/views/layouts/_head_tags.html.haml
%title Email Dashboard
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
/ Required meta tags
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
/ UIKit CSS
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.38/css/uikit.min.css", :rel => "stylesheet"}/

= csrf_meta_tags
/ UIKit JS.
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.38/js/uikit.min.js"}
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.38/js/uikit-icons.min.js"}

= javascript_pack_tag 'application'
= stylesheet_pack_tag 'application'

rails-dashboard/app/views/layouts/_head_tools.html.haml
.uk-navbar-container.uk-navbar{style: 'background-color: #ffffff'}
  .uk-navbar-left
    %ul.uk-breadcrumb{style: 'padding: 17px;'}
      = render_breadcrumbs :tag => :li, :separator => ""

  .uk-navbar-right
    - if content_for?(:action_buttons)
      = yield :action_buttons

rails-dashboard/app/views/layouts/_navbar.html.haml
%nav.uk-navbar-container{"uk-navbar" => ""}
  .uk-navbar-left
    %ul.uk-navbar-nav
      %li.uk-active
        %a
          %span{"uk-icon" => "icon: bell"}
      %li{class: "#{'uk-active' if (current_page?(root_path) || current_page?(dashboards_path))}"}
        %a{:href => root_path}= t('dashboard.home.title')
      %li{class: "#{'uk-active' if current_page?(activities_path)}"}
        %a{:href => activities_path }= t('dashboard.activities.title')
      %li{class: "#{'uk-active' if current_page?(notifications_path)}"}
        %a{:href => notifications_path }= t('dashboard.notifications.title')
      %li{class: "#{'uk-active' if current_page?(smtp_settings_path)}"}
        %a{:href => smtp_settings_path }= t('dashboard.smtp.title')
      %li{class: "#{'uk-active' if current_page?(notification_contents_path)}"}
        %a{:href => notification_contents_path }= t('dashboard.templates.title')
  .uk-navbar-right
    %ul.uk-navbar-nav
      %li
        %a{:href => "#"}
          = current_account.try(:name) || t('accounts.no_account')
          %span{"uk-icon" => "icon: chevron-down"}
        .uk-navbar-dropdown
          %ul.uk-nav.uk-dropdown-nav
            - current_user.accounts.persisted.each do |account|
              %li{class: ('uk-active' if account == current_account) }
                = link_to set_current_account_path(account), method: :post do
                  = account.name
                  %span.uk-float-right
                    .uk-badge{class: (account.live_mode ? 'uk-label-success' : 'uk-metal')}
            %li.uk-nav-divider
            %li
              = link_to t('accounts.manage'), accounts_path
      %li
        %a{:href => "#"}
          = current_user.email
          %span{"uk-icon" => "icon: chevron-down"}
        .uk-navbar-dropdown
          %ul.uk-nav.uk-navbar-dropdown-nav
            %li
              = link_to t('auth.profile_settings'), edit_user_registration_path, class: 'dropdown-item'
            %li.uk-nav-divider
            %li
              = link_to t('auth.logout'), destroy_user_session_path, class: 'dropdown-item', method: :delete

rails-dashboard/app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render partial: 'layouts/head_tags'
    / Import highlight.js
    %link{:href => "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/tomorrow-night.min.css", :rel => "stylesheet"}/
    %script{:src => "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"}

  %body.uk-background-default

    = render 'layouts/navbar'

    .uk-container
      = render partial: 'layouts/head_tools'

      = yield

    #modal-holder

    %footer.uk-text-center.uk-text-muted.uk-background-muted
      .uk-margin
      = t('main.footer.crafted_with')
      %i{'uk-icon': 'heart', style: 'color: red'}
      = t('main.footer.sunny_california')
      .uk-margin

    - flash.each do |key, value|
      :javascript
        UIkit.notification({message: "#{value}", status: "#{flash_class(key)}", pos: 'bottom-right'})

rails-dashboard/app/views/layouts/devise.html.haml
!!!
%html{:lang => "en"}
  %head
    = render partial: 'layouts/head_tags'
  %body.uk-background-default
    %nav.uk-navbar-container{"uk-navbar" => ""}
      .uk-navbar-left
        %ul.uk-navbar-nav
          %li.uk-active
            %a
              %span{"uk-icon" => "icon: bell"}
    .uk-container
      %div{:class => "uk-child-width-1-2@m", "uk-grid" => ""}
        %div
          .uk-card
            .uk-card-body
              %h3.uk-card-title= t('main.welcome_to_email_dashboard')
              %p= t('main.features.post_variables')
              %p= t('main.features.manage_notifications')
              %p= t('main.features.customize')
        %div
          .uk-card
            .uk-card-body
              = yield

    / Footer
    %footer.uk-text-center.uk-text-muted.uk-background-muted
      .uk-margin
      = t('main.footer.crafted_with')
      %i{'uk-icon': 'heart', style: 'color: red'}
      = t('main.footer.sunny_california')
      .uk-margin

rails-dashboard/app/views/layouts/modal.html.haml
#modal-sections.modal{"uk-modal" => ""}
  .uk-modal-dialog
    %button.uk-modal-close-default{:type => "button", "uk-close" => ""}
    .uk-modal-header
      %h6.uk-modal-title{style: 'font-size: 1.2rem;'}
        = yield :modal_title if content_for? :modal_title
    .uk-modal-body
      = yield
    .uk-modal-footer.uk-text-right
      %button.uk-button.uk-button-default.uk-modal-close{:type => "button"}= t('modal.close')