rails-dashboard/config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }, path: 'auth'

  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'registrations#new', as: :unauthenticated_root
    end
  end

  root 'dashboards#index'

  resources :notifications do
    resources :notification_delivers, only: :update
  end

  resources :smtp_settings, path: 'smtp'
  resources :accounts do
    member do
      post :set_current
    end
  end

  resource :trackings
  resource :test_modes

  resources :invitations, only: %i[create update]

  resources :notification_contents, path: 'templates' do
    member do
      get :preview
    end
  end

  resources :activities, only: %i[index show] do
    resource :schedulers, only: %i[show update]
  end

  resources :dashboards, only: :index
end

rails-dashboard/app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  account_id :integer
#  slug       :string(255)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Notification < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :account

  has_many :notification_delivers

  validates :name, presence: true

  after_create :create_delivers

  def email_deliver
    notification_delivers.where(delivery_method: 'email').first
  end

  private

  def create_delivers
    notification_delivers.create(smtp_setting: account.smtp_settings.first,
                                 notification_content: account.notification_contents.first,
                                 delivery_method: 'email')
  end
end

rails-dashboard/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  include BreadcrumbExtension

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = current_account.notifications.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    add_breadcrumb @notification.name, notification_path(@notification)

    @activities = Activity.where(notification_deliver_id: @notification.email_deliver.id)
                          .order('created_at desc').page(params[:page])
  end

  # GET /notifications/new
  def new
    @notification = current_account.notifications.new
  end

  # GET /notifications/1/edit
  def edit
    add_breadcrumb @notification.name, notification_path(@notification)
    super
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = current_account.notifications.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: I18n.t('notifications.flash.create_success') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: I18n.t('notifications.flash.success_update') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: I18n.t('notifications.flash.success_destroy') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = current_account.notifications.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:name)
    end
end

rails-dashboard/app/views/notifications/_activity_content.html.erb
<div style="background-color:white">
  <%= (ap JSON.parse(activity.request_content) , { color: { hash: :blue }, html: false }).html_safe %>
</div>

rails-dashboard/app/views/notifications/_blank.html.haml
%div{style: "text-align: center;"}
  .uk-text-muted
    = t('notifications.not_created_yet')
  %br/
  = link_to t('actions.create_new'), new_notification_path, class: 'uk-button uk-button-success'

rails-dashboard/app/views/notifications/_code_block.html.erb
<% variables = @notification.try(:email_deliver).try(:notification_content).present? ? @notification.email_deliver.notification_content.content_variables : [] %>

<ul uk-tab class="uk-tab">
  <li class="uk-active"><a href="#">Curl</a></li>
  <li><a href="#">Ruby</a></li>
  <li><a href="#">Postman</a></li>
</ul>
<!-- Tab panes -->
<ul class="uk-switcher uk-margin">
  <li class="uk-active" id="curl" role="tabpanel">
    <pre>
      <code class="hljs bash" style="margin-left: -50px;">
      # Test Mode API Key: <%= current_account.test_api_key %>
      # Live Mode API Key: <%= current_account.api_key %>
      curl -i -H "Authorization: Token <%= current_account.api_key %>" -H "Content-type: application/json" \
      -X POST -d '{ "variables": { "<%= variables.first || 'variable' %>": "Test", "button_name": "Click Me!"}, "email":{ "to":["test-to@email.com"], "from":"test-from@email.com" } }' \
      <%= "\"#{ENV['REST_API_URL'] || 'http://localhost:8080' }/api/v3/notifications/#{@notification.slug}\"" %>

      # <%= t('notifications.docs.delivery_optional') %>
      # <u><a href="https://en.wikipedia.org/wiki/List_of_tz_database_time_zones" target="_blank"><%= t('notifications.docs.available_timezone') %></a></u>
      # Example JSON body
        {
          "variables":{
             "user_fullname":"Test User"
          },
          "email":{
             "to":["test@gmail.com", "test2@gmail.com"],
             "cc": ["cc@test.com"],
             "reply_to": ["reply@test.com"],
             "from":"from@test.com"
          },
          "delivery": {
            "time": "21:00",
            "date": "2018-02-12",
            "zone": "Etc/UTC"
          }
       }
      </code>
    </pre>
  </li>
  <li class="tab-pane" id="ruby" role="tabpanel">
    <pre>
      <code class="hljs ruby" style="margin-left: -50px;">
      # Test Mode API Token: test_<%= current_account.api_key %>
      # Live Mode API Token: <%= current_account.api_key %>
      require 'httparty'

        body = {
          email: {
            to: ['to@example.com'],
            cc: ['cc@test.com'],
            bcc: ['bcc@test.com'],
            from: 'from@test.com',
            reply_to: ['reply@test.com']
          },
          variables: {
          <% variables.each do |variable| %>
            <%= "#{variable}: 'some_value'," %>
          <% end %>
          },
          delivery: { # optional
            time: "21:00",
            date: "<%= Time.current.to_date %>",
            time_zone: "Etc/UTC" # <u><a href="https://en.wikipedia.org/wiki/List_of_tz_database_time_zones" target="_blank">See available timezones.</a></u>
          }
        }
        headers = {
          <%= "Authorization: \"Token #{current_account.api_key}\"" %>
        }

        HTTParty.post(
          '"https://api.<%= request.domain %>/api/v3/notifications/<%= @notification.slug %>"',
          body: body.to_json, headers: headers
        )
      </code>
    </pre>
  </li>
  <li class="tab-pane" id="postman" role="tabpanel">
    <%= link_to 'Download Postman Collection', '/Notification-Dashboard.postman_collection.json', download: '' %>
  </li>
</ul>

rails-dashboard/app/views/notifications/_form.html.haml
.uk-card.uk-card-default.uk-card-body
  = simple_form_for(@notification,  html: { class: 'form-horizontal' }) do |f|
    = f.error_notification
    .uk-margin
      = f.input :name, label: t('notifications.form.name'), input_html: { class: 'uk-input' }

    = f.submit t('actions.save'), class: 'uk-button uk-button-primary'

rails-dashboard/app/views/notifications/_index.html.haml
%table.uk-table.uk-table-responsive.uk-table-divider
  %thead
    %tr
      %th= t('notifications.form.name')
      %th= t('notifications.form.is_active')
      %th
  %tbody
    - notifications.each do |notification|
      %tr
        %td= notification.name
        %td
          %span.uk-label{class: "uk-label-#{notification.email_deliver.is_active ? 'success' : 'danger'}"}
            = notification.email_deliver.is_active ? 'yes' : 'no'
        %td.uk-text-right
          = link_to t('actions.settings'), notification, class: 'uk-button uk-button-small uk-button-default'
          = link_to t('actions.destroy'), notification, class: 'uk-button uk-button-small uk-button-danger',  method: :delete, data: { confirm: t('confirm.are_you_sure') }

rails-dashboard/app/views/notifications/edit.html.haml
= render 'form', notification: @notification

rails-dashboard/app/views/notifications/index.html.haml
= content_for :action_buttons do
  = link_to new_notification_path, class: 'uk-button uk-button-success' do
    %i{'uk-icon': 'plus'}
    = t('notifications.new_notification')


- if @notifications.size == 0
  = render 'notifications/blank'
- else
  = render 'notifications/index', { notifications: @notifications }

rails-dashboard/app/views/notifications/new.html.haml
= render 'form', notification: @notification

rails-dashboard/app/views/notifications/show.html.haml
= content_for :action_buttons do
  = link_to t('notifications.go_to_docs'), '#doc-ntf', 'uk-scroll': '', class: 'uk-text-right uk-button uk-button-default'

.uk-card.uk-card-default.uk-card-body
  %p
    %strong= @notification.name
    = link_to t('actions.edit'), edit_notification_path(@notification), class: 'uk-button uk-button-small uk-button-default'
.uk-margin

.uk-grid-collapse{'uk-grid': '', class: 'uk-child-width-expand@s'}
  .uk-card.uk-card-default.uk-card-body
    = simple_form_for([@notification, @notification.email_deliver],  html: { class: 'form-horizontal' }, method: :patch) do |f|
      %fieldset.uk-fieldset
        = f.error_notification
        %h3
        .uk-margin.uk-grid-small.uk-child-width-auto.uk-grid
          = f.input :is_active, label: t('notifications.form.is_active'), input_html: { class: 'uk-checkbox uk-form-width-medium', style: 'margin-right: 5px;' }
        .uk-margin
          %label.uk-form-label= t('smtp.settings')
          = f.association :smtp_setting, label_method: :provider, value_method: :id, label: false, include_blank: true, required: true, collection: current_account.smtp_settings, input_html: { class: 'uk-select uk-form-width-large' }
        .uk-margin
          %label.uk-form-label= t('notifications.form.template')
          = f.association :notification_content, label_method: :subject, value_method: :id, label: false, include_blank: true, required: true, collection: current_account.notification_contents, input_html: { class: 'uk-select uk-form-width-large' }
      .uk-margin
        = f.submit t('actions.save'), class: 'uk-button uk-button-primary'

.uk-margin#doc-ntf
.uk-card.uk-card-default.uk-card-body
  = render 'code_block'

.uk-margin
.uk-card.uk-card-default.uk-card-body
  %h3.text-center= t('dashboard.activities.title')

  = render partial: 'activities/index', locals: { activities: @activities }