rails-dashboard/config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }, path: 'auth'

  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'registrations#new', as: :unauthenticated_root
    end
  end

  root 'dashboards#index'

  resources :notifications do
    resources :notification_delivers, only: :update
  end

  resources :smtp_settings, path: 'smtp'
  resources :accounts do
    member do
      post :set_current
    end
  end

  resource :trackings
  resource :test_modes

  resources :invitations, only: %i[create update]

  resources :notification_contents, path: 'templates' do
    member do
      get :preview
    end
  end

  resources :activities, only: %i[index show] do
    resource :schedulers, only: %i[show update]
  end

  resources :dashboards, only: :index
end

rails-dashboard/app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id                      :integer          not null, primary key
#  notification_deliver_id :integer
#  request_content         :json
#  status                  :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  error_message           :string(255)
#

class Activity < ApplicationRecord
  belongs_to :notification_deliver

  has_many :receivers

  STATUSES = %w[pending scheduled fail success canceled].freeze

  TRACK_STATUSES = {
    sent: 'Sent',
    delivery: 'Deliveried',
    bounce: 'Bounced',
    complaint: 'Complained'
  }
end

rails-dashboard/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activities, :set_custom_breadcrumbs
  before_action :authorize_view_token, only: :show

  def index
    @activities = @activities.where(request_mode_is_live: true) unless session[:show_test_mode] == 'enabled'

    @q = @activities.ransack(params[:q])
    @q.sorts = 'send_at DESC'
    @list_activities = @q.result(distinct: true).page(params[:page])
  end

  def show
    @activity = @activities.find(params[:id])
    add_breadcrumb @activity.id

    content  = @activity.request_content
    template = @activity.notification_deliver.notification_content.content
    subject  = @activity.notification_deliver.notification_content.subject

    handlebars = Handlebars::Context.new
    email_template = handlebars.compile(template)

    @activity_variables = email_template.call(content['variables'])

    email_subject = handlebars.compile(subject)
    @activity_subject = email_subject.call(content['variables'])

    @activity_email   = content['email']

    respond_to do |format|
      format.html { render 'activities/show', layout: false }
    end
  end

  private

  def set_custom_breadcrumbs
    add_breadcrumb I18n.t('dashboard.activities.title'), activities_path
  end

  def authorize_view_token
    if params[:token].present?
      decoded_token = JWT.decode params[:token], nil, false

      # View token expires in 15 minutes
      if Time.current > (Time.at(decoded_token.first['data']) + 15.minutes)
        redirect_to activities_path, flash: { error: 'View token expired! Please try again...' }
      end
    else
      redirect_to activities_path, flash: { error: 'View token required!' }
    end
  end

  def set_activities
    @activities = Activity.joins(notification_deliver: :notification)
                          .where('notifications.account_id = ?', current_account.id)
  end
end

rails-dashboard/app/views/activities/_blank.html.haml
%div{style: "text-align: center;"}
  .uk-text-muted= t('dashboard.activities.no_activity')

rails-dashboard/app/views/activities/_index.html.haml
%table.uk-table.uk-table-responsive.uk-table-divider
  %thead
    %tr
      %th= t('dashboard.activities.fields.sent_at')
      %th= t('dashboard.activities.fields.notification')
      %th= t('dashboard.activities.fields.status')
      %th
  %tbody
    - activities.includes(notification_deliver: :notification).each do |activity|
      %tr
        %td= activity.send_at || activity.created_at
        %td
          - if activity.notification_deliver.try(:notification).present?
            = link_to activity.notification_deliver.notification.name, notification_path(activity.notification_deliver.notification)
        %td
          = badge_status(activity.status)
          = tracking_status(activity.track_status)
          - unless activity.request_mode_is_live
            %span.uk-badge{style: 'background: #909fad', 'uk-tooltip': "title: Test Mode"}
          - if activity.error_message.present?
            %span.uk-margin-small-right.uk-icon{'uk-icon': 'info', 'uk-tooltip': "title: #{activity.error_message}"}
          - elsif activity.status == 'scheduled'
            = link_to activity_schedulers_path(activity), data: { modal: true } do
              %span.uk-margin-small-right.uk-icon{'uk-icon': 'cog', 'uk-tooltip': "title: Scheduled to: #{activity.send_at}"}
        - payload = { data: Time.current.to_i, id: activity.id }
        %td= link_to t('dashboard.activities.fields.content_preview'), activity_path(activity, token: (JWT.encode payload, nil, 'none')), class: 'uk-button uk-button-small uk-button-default', target: '_blank'

= paginate activities

rails-dashboard/app/views/activities/index.html.haml
= content_for :action_buttons do
  %small.uk-margin-right Show test mode activities
  %label.uk-switch.uk-light{:for => "testModeCheck"}
    %input#testModeCheck{:type => "checkbox", "#{'checked' if session[:show_test_mode].present?}": ''}/
    .uk-switch-slider

.uk-grid-collapse.uk-text-center{:class => "uk-child-width-expand@s", "uk-grid" => ""}
  %div
    .uk-label-success.uk-padding-small.uk-light
      = link_to activities_path(q: { status_eq: 'success' }) do
        = t('dashboard.activities.status.success')
        = @activities.where(status: 'success').count

  %div
    .uk-background-primary.uk-padding-small.uk-light
      = link_to activities_path(q: { status_eq: 'pending' }) do
        = t('dashboard.activities.status.pending')
        = @activities.where(status: 'pending').count
  %div
    .uk-label-warning.uk-padding-small.uk-light
      = link_to activities_path(q: { status_eq: 'scheduled' }) do
        = t('dashboard.activities.status.scheduled')
        = @activities.where(status: 'scheduled').count
  %div
    .uk-label-danger.uk-padding-small.uk-light
      = link_to activities_path(q: { status_eq: 'fail' }) do
        = t('dashboard.activities.status.failed')
        = @activities.where(status: 'fail').count
  %div
    .uk-background-secondary.uk-padding-small.uk-light
      = link_to activities_path(q: { status_eq: 'canceled' }) do
        = t('dashboard.activities.status.canceled')
        = @activities.where(status: 'canceled').count

- if @list_activities.size == 0
  .uk-padding
  = render partial: 'activities/blank'
- else
  = render partial: 'activities/index', locals: { activities: @list_activities }

rails-dashboard/app/views/activities/show.html.haml
%table{style: 'width: 40%;margin-left: 30%;margin-top: 2%;border: 1px solid black;'}
  - @activity_email.each do |key, value|
    %tr
      %td
        %b= "#{key}:"
      %td= value.is_a?(Array) ? value.join(', ') : value

%h2{style: 'text-align: center;margin: 10px;'}
  = raw @activity_subject
= raw @activity_variables