rails-dashboard/config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions' }, path: 'auth'

  devise_scope :user do
    authenticated :user do
      root to: 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'registrations#new', as: :unauthenticated_root
    end
  end

  root 'dashboards#index'

  resources :notifications do
    resources :notification_delivers, only: :update
  end

  resources :smtp_settings, path: 'smtp'
  resources :accounts do
    member do
      post :set_current
    end
  end

  resource :trackings
  resource :test_modes

  resources :invitations, only: %i[create update]

  resources :notification_contents, path: 'templates' do
    member do
      get :preview
    end
  end

  resources :activities, only: %i[index show] do
    resource :schedulers, only: %i[show update]
  end

  resources :dashboards, only: :index
end

rails-dashboard/app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  slug       :string(255)
#  api_key    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :notifications
  has_many :smtp_settings, dependent: :destroy
  has_many :notification_contents, dependent: :destroy

  has_many :account_users, dependent: :destroy
  has_many :users, through: :account_users

  before_create :generate_token

  after_create  :create_default_email_template

  scope :persisted, -> { where.not(id: nil) }

  protected

  def generate_token
    self.api_key = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Account.exists?(api_key: random_token)
    end

    self.test_api_key = loop do
      random_token = "test_#{SecureRandom.urlsafe_base64(nil, false)}"
      break random_token unless Account.exists?(test_api_key: random_token)
    end
  end

  private

  def create_default_email_template
    require 'open-uri'
    doc = Nokogiri::HTML(open("https://s3.amazonaws.com/contents-notification/default_template.html"))
    notification_contents.create(subject: "HTML Test Content", content: doc.to_s)
  end
end

rails-dashboard/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:edit, :update, :set_current, :destroy]
  before_action :check_owner_access, only: [:edit, :update, :destroy]

  include BreadcrumbExtension

  def index
    @accounts = current_user.accounts
  end

  def new
    @account = current_user.accounts.new
  end

  def edit
    add_breadcrumb @account.name
    super
  end

  def create
    new_account = current_user.setup_account(account_params[:name])
    session[:current_account_id] = new_account.id
    respond_to do |format|
      format.html { redirect_to accounts_path, notice: I18n.t('accounts.flash.successfully_created') }
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to edit_account_path(@account), notice: I18n.t('accounts.flash.successfully_updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if !@account.notifications.present? && @account.destroy
        format.html { redirect_to accounts_url, notice: I18n.t('accounts.flash.successfully_destroyed') }
      else
        format.html { redirect_to accounts_url, flash: { error: I18n.t('accounts.flash.can_not_destroy') } }
      end
    end
  end

  def set_current
    session[:current_account_id] = @account.id
    redirect_to root_path
  end

  private

  def check_owner_access
    if current_user.role_in_account(@account) != 'owner'
      redirect_to(accounts_path, flash: { error: I18n.t('accounts.flash.no_access') }) && return
    end
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = current_user.accounts.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :live_mode, :to_email_for_test)
  end
end

rails-dashboard/app/views/accounts/_blank.html.haml
%div{style: "text-align: center;"}
  .uk-text-muted
    = t('accounts.not_created_yet')
    %br/
    = link_to t('actions.create_new') ,new_account_path, class: 'uk-button uk-button-success'

rails-dashboard/app/views/accounts/_form.html.haml
.uk-card.uk-card-default.uk-card-body
  %h3.text-center= t('accounts.form.info')
  = simple_form_for(account,  html: { class: 'form-horizontal' }) do |f|
    = f.error_notification
    .uk-margin
      = f.input :name, label: t('accounts.form.name'), input_html: { class: 'uk-input' }, required: true, autofocus: true

    = f.submit t('actions.save'), class: 'uk-button uk-button-primary'

rails-dashboard/app/views/accounts/_index.html.haml
%table.uk-table.uk-table-responsive.uk-table-divider
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td.uk-text-right
          = link_to 'Dashboard', set_current_account_path(account), method: :post, class: 'uk-button uk-button-small uk-button-default'
          = link_to 'Settings', edit_account_path(account), class: 'uk-button uk-button-small uk-button-default'
          = link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'uk-button uk-button-small uk-button-danger'

rails-dashboard/app/views/accounts/edit.html.haml
.uk-margin
.uk-card.uk-card-default.uk-card-body
  %h3.text-center
    Live Mode / Test Mode

  = simple_form_for(@account,  html: { class: 'form-horizontal' }) do |f|
    %p
      %b Live Mode API Token:
      = @account.api_key
    %p
      %b Test Mode API Token:
      = @account.test_api_key
    = f.error_notification
    .uk-margin
    %div
      %label= t('accounts.info.test_mode_email')
      = f.input :to_email_for_test, input_html: { class: 'uk-input uk-form-width-large' }, autofocus: true, label: false, placeholder: 'example@email.com'
      %p.uk-text-danger
        %i= t('accounts.warnings.notifications_not_send_to_real_address')

    .uk-margin
    = f.submit t('actions.save'), class: 'uk-button uk-button-primary'


.uk-margin
= render 'form', account: @account

.uk-margin
.uk-card.uk-card-default.uk-card-body
  %h3.text-center= t('accounts.team.members')
  = simple_form_for(:invitation,  html: { class: 'form-horizontal' }, url: invitations_path, method: :post) do |f|
    .uk-margin
      = f.input :email, label: t('accounts.form.email'), placeholder: 'email@example.com', input_html: { class: 'uk-input' }
      = f.input :account, :as => :hidden, :input_html => { :value => @account.id }
    = f.submit t('accounts.form.invite'), class: 'uk-button uk-button-primary'
  %br

  %table.uk-table.uk-table-responsive.uk-table-divider
    %thead
      %tr
        %th #
        %th= t('accounts.form.email')
        %th= t('accounts.form.role')
        %th
    %tbody
      - @account.account_users.each do |au|
        %tr
          %td= au.id
          %td= au.user.email
          %td= au.role
          %td
            - unless au.role == 'owner'
              = link_to invitation_path(au.id, account_id: @account.id), method: :patch do
                %span.badge.badge-pill.badge-default
                  = t('accounts.team.resend_confirm')

rails-dashboard/app/views/accounts/index.html.haml
= content_for :action_buttons do
  = link_to new_account_path, class: 'uk-button uk-button-success' do
    %i{'uk-icon': 'plus'}
    = t('accounts.new_account')

- if @accounts.size == 0
  = render 'accounts/blank'
- else
  = render 'accounts/index'

rails-dashboard/app/views/accounts/new.html.haml
= render 'form', account: @account